---
name: Text-Modify
version: 0.4
author:
  - Roland Lammel (lammel@cpan.org)
abstract: 'oo-style interface for simple, rule-based text modification'
license: perl
provides:
  Text::Buffer:
    file: lib/Text/Buffer.pm
    version: 0.4
  Text::Modify:
    file: lib/Text/Modify.pm
    version: 0.4
  Text::Modify::Rule:
    file: lib/Text/Modify/Rule.pm
    version: 0.4
generated_by: Module::Build version 0.26
