--- #YAML:1.0
name: Text-Modify
version: 0.3
author:
  - Roland Lammel (lammel@cpan.org)
abstract: oo-style interface for simple, rule-based text modification
license: perl
generated_by: Module::Build version 0.2608, without YAML.pm
